### ISSUE TITLE
docker daemon is not running

### ISSUE THREAD

**Issue by marufaytekin** [mrohland/gocd-docker#1]
Docker daemon is not running in gocd-agent, therefore I cannot build docker image in gocd agent. I used the Dockerfile as is.

root@ad0a4eb69e89:/tmp# docker version  
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

**Comment by mrohland** [comment]
These files where just some try-out last summer. I'm surprised that anything in them works. If you want to use gocd inside docker better consider using the officially maintained ones at https://github.com/gocd/gocd-docker
